const STORAGE_KEY='karkasnik-crm-v3';
const PREV_KEY='karkasnik-crm-v2';
const OLD_KEY='karkasnik-crm-v1';
const SALES_STAGES=['Новая заявка','Замер','Расчёт','Переговоры','Договор','Стройка','Сдано','Отказ'];
const BUILD_STAGES=['Фундамент','Каркас','Кровля','Окна и двери','Утепление','Инженерия','Внутренняя отделка','Фасад','Сдача'];
let activeSalesFilter='Все';
let activeObjectTab='overview';
let state=load();

function load(){
  try{
    for(const key of [STORAGE_KEY,PREV_KEY,OLD_KEY]){
      const raw=localStorage.getItem(key);
      if(raw){const s=normalize(JSON.parse(raw));localStorage.setItem(STORAGE_KEY,JSON.stringify(s));return s}
    }
  }catch{}
  return{clients:[],orders:[]};
}
function normalize(data){
  const s={clients:Array.isArray(data?.clients)?data.clients:[],orders:Array.isArray(data?.orders)?data.orders:[]};
  s.orders=s.orders.map(o=>({...o,status:mapOldStatus(o.status),buildStages:o.buildStages||defaultBuildStages(),expenses:o.expenses||[],team:o.team||[],documents:o.documents||[],photos:o.photos||[],history:o.history||[]}));
  return s;
}
function mapOldStatus(v){return({'Новый':'Новая заявка','Расчёт':'Расчёт','Договор':'Договор','В работе':'Стройка','Завершён':'Сдано','Отказ':'Отказ'})[v]||v||'Новая заявка'}
function defaultBuildStages(){return BUILD_STAGES.map(name=>({name,done:false}))}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll();refreshOpenObject()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function money(v){return new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ₽'}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function client(id){return state.clients.find(c=>c.id===id)}
function clientName(id){return client(id)?.name||'Без клиента'}
function isBuild(o){return ['Стройка','Сдано'].includes(o.status)}
function progress(o){const list=o.buildStages||defaultBuildStages();return Math.round((list.filter(s=>s.done).length/list.length)*100)}
function expenseTotal(o){return (o.expenses||[]).reduce((s,x)=>s+(Number(x.amount)||0),0)}
function badgeClass(status){if(status==='Стройка')return'build';if(status==='Сдано')return'done';if(status==='Отказ')return'off';if(['Договор','Переговоры'].includes(status))return'hot';return''}
function addHistory(o,text){o.history=o.history||[];o.history.unshift({id:uid(),date:new Date().toLocaleString('ru-RU'),text})}

function renderStats(){
  const pipeline=state.orders.filter(o=>!['Сдано','Отказ'].includes(o.status));
  const builds=state.orders.filter(o=>o.status==='Стройка');
  document.querySelector('#statDeals').textContent=pipeline.length;
  document.querySelector('#statBuilds').textContent=builds.length;
  document.querySelector('#statRevenue').textContent=money(state.orders.filter(o=>o.status!=='Отказ').reduce((s,o)=>s+(Number(o.price)||0),0));
  document.querySelector('#statPaid').textContent=money(state.orders.reduce((s,o)=>s+(Number(o.prepayment)||0),0));
}
function renderClientOptions(){
  const sel=document.querySelector('#orderClient');
  sel.innerHTML=state.clients.length?'<option value="">Выберите клиента</option>'+state.clients.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.phone)}</option>`).join(''):'<option value="">Сначала добавьте клиента</option>';
}
function renderFunnel(){
  const stages=SALES_STAGES.filter(x=>!['Стройка','Сдано','Отказ'].includes(x));
  document.querySelector('#funnelSummary').innerHTML=stages.map(stage=>{const rows=state.orders.filter(o=>o.status===stage);return `<div class="funnel-item"><span>${stage}</span><strong>${rows.length}</strong><small>${money(rows.reduce((s,o)=>s+(Number(o.price)||0),0))}</small></div>`}).join('');
}
function renderSalesFilters(){document.querySelector('#salesFilters').innerHTML=['Все',...SALES_STAGES].map(s=>`<button class="filter-chip ${activeSalesFilter===s?'active':''}" onclick="setSalesFilter('${s}')">${s}</button>`).join('')}
function clientCard(c){const orders=state.orders.filter(o=>o.clientId===c.id);const active=orders.filter(o=>!['Сдано','Отказ'].includes(o.status)).length;return `<article class="card"><div class="card-top"><div><h4>${esc(c.name)}</h4><div class="muted">${esc(c.phone)}${c.city?' · '+esc(c.city):''}</div></div><span class="badge">${active} активн.</span></div><div class="meta">${c.messenger?`<div>💬 ${esc(c.messenger)}</div>`:''}${c.address?`<div>📍 ${esc(c.address)}</div>`:''}<div>Источник: ${esc(c.source||'—')}</div>${c.comment?`<div>${esc(c.comment)}</div>`:''}</div><button class="danger-link" onclick="deleteClient('${c.id}')">Удалить клиента</button></article>`}
function orderCard(o){const c=client(o.clientId);const debt=Math.max(0,(Number(o.price)||0)-(Number(o.prepayment)||0));return `<article class="card"><div class="card-top"><div><h4>${esc(c?.name||'Без клиента')}</h4><div class="muted">${esc(o.size||'Размер не указан')}${o.area?' · '+esc(o.area)+' м²':''}${c?.phone?' · '+esc(c.phone):''}</div></div><span class="badge ${badgeClass(o.status)}">${esc(o.status)}</span></div><div class="meta"><div>${esc(o.package||'—')} · <strong>${money(o.price)}</strong></div><div>Получено: ${money(o.prepayment)} · Остаток: ${money(debt)}</div>${o.deadline?`<div class="muted">План сдачи: ${esc(o.deadline)}</div>`:''}${o.comment?`<div>${esc(o.comment)}</div>`:''}</div><div class="deal-actions"><button class="text-btn" onclick="openDeal('${o.id}')">Открыть сделку</button>${isBuild(o)?`<button class="text-btn" onclick="openObject('${o.id}')">Карточка объекта</button>`:''}${o.status==='Договор'?`<button class="text-btn" onclick="moveToBuild('${o.id}')">Передать в стройку</button>`:''}</div></article>`}
function buildCard(o,compact=false){const p=progress(o);const stages=o.buildStages||defaultBuildStages();const stageRows=compact?'':`<div class="stage-list">${stages.map((s,i)=>`<div class="stage-row"><label><input type="checkbox" ${s.done?'checked':''} onchange="toggleBuildStage('${o.id}',${i})">${esc(s.name)}</label><span class="muted">${s.done?'Готово':'В работе'}</span></div>`).join('')}</div>`;return `<article class="card"><div class="card-top"><div><h4>${esc(clientName(o.clientId))} · ${esc(o.size||'Дом')}</h4><div class="muted">${o.area?esc(o.area)+' м² · ':''}${esc(o.package||'')}</div></div><span class="badge ${o.status==='Сдано'?'done':'build'}">${o.status}</span></div><div class="build-progress"><i style="width:${p}%"></i></div><div class="progress-label"><span>Готовность объекта</span><strong>${p}%</strong></div><div class="meta"><div>Расходы: ${money(expenseTotal(o))}</div>${o.team?.length?`<div>Бригада: ${o.team.length} чел.</div>`:''}${o.deadline?`<div>План сдачи: ${esc(o.deadline)}</div>`:''}</div><div class="deal-actions"><button class="text-btn" onclick="openObject('${o.id}')">Карточка объекта</button></div>${stageRows}</article>`}
function renderClients(){const q=document.querySelector('#clientSearch').value.trim().toLowerCase();const list=state.clients.filter(c=>[c.name,c.phone,c.city,c.address,c.source].join(' ').toLowerCase().includes(q));document.querySelector('#clientList').innerHTML=list.length?list.slice().reverse().map(clientCard).join(''):'<div class="empty">Клиентов пока нет</div>'}
function renderOrders(){const q=document.querySelector('#orderSearch').value.trim().toLowerCase();let list=state.orders.filter(o=>[clientName(o.clientId),client(o.clientId)?.phone,o.size,o.status,o.package].join(' ').toLowerCase().includes(q));if(activeSalesFilter!=='Все')list=list.filter(o=>o.status===activeSalesFilter);document.querySelector('#orderList').innerHTML=list.length?list.slice().reverse().map(orderCard).join(''):'<div class="empty">Сделок не найдено</div>'}
function renderBuilds(){const q=document.querySelector('#buildSearch').value.trim().toLowerCase();const list=state.orders.filter(o=>isBuild(o)&&[clientName(o.clientId),o.size,o.package].join(' ').toLowerCase().includes(q));document.querySelector('#buildList').innerHTML=list.length?list.slice().reverse().map(o=>buildCard(o,false)).join(''):'<div class="empty">Объектов в стройке пока нет</div>'}
function renderBuildSummary(){const list=state.orders.filter(o=>o.status==='Стройка').slice(-3).reverse();document.querySelector('#buildSummary').innerHTML=list.length?list.map(o=>buildCard(o,true)).join(''):'<div class="empty">Когда сделка перейдёт в «Стройка», объект появится здесь</div>'}
function renderAll(){renderStats();renderClientOptions();renderFunnel();renderSalesFilters();renderClients();renderOrders();renderBuilds();renderBuildSummary()}

window.setSalesFilter=s=>{activeSalesFilter=s;renderSalesFilters();renderOrders()};
window.deleteClient=id=>{if(!confirm('Удалить клиента и все его сделки?'))return;state.clients=state.clients.filter(c=>c.id!==id);state.orders=state.orders.filter(o=>o.clientId!==id);save()};
window.openDeal=id=>{const o=state.orders.find(x=>x.id===id);if(!o)return;const c=client(o.clientId);const f=document.querySelector('#dealForm');f.id.value=o.id;f.status.value=o.status;f.price.value=o.price||'';f.prepayment.value=o.prepayment||'';f.startDate.value=o.startDate||'';f.deadline.value=o.deadline||'';f.comment.value=o.comment||'';document.querySelector('#dealTitle').textContent=c?.name||'Сделка';document.querySelector('#dealInfo').innerHTML=`<strong>${esc(o.size||'Дом')} ${o.area?'· '+esc(o.area)+' м²':''}</strong><br>${esc(o.package||'—')}${c?.phone?'<br>'+esc(c.phone):''}`;document.querySelector('#dealModal').showModal()};
window.moveToBuild=id=>{const o=state.orders.find(x=>x.id===id);if(!o)return;o.status='Стройка';if(!o.buildStages)o.buildStages=defaultBuildStages();addHistory(o,'Объект передан в стройку');save();switchView('builds')};
window.toggleBuildStage=(id,index)=>{const o=state.orders.find(x=>x.id===id);if(!o)return;if(!o.buildStages)o.buildStages=defaultBuildStages();o.buildStages[index].done=!o.buildStages[index].done;addHistory(o,`${o.buildStages[index].name}: ${o.buildStages[index].done?'этап завершён':'этап возвращён в работу'}`);if(o.buildStages.every(s=>s.done)){o.status='Сдано';addHistory(o,'Объект полностью завершён')}save()};

window.openObject=id=>{const o=state.orders.find(x=>x.id===id);if(!o)return;document.querySelector('#objectId').value=id;activeObjectTab='overview';renderObject();document.querySelector('#objectModal').showModal()};
function refreshOpenObject(){const d=document.querySelector('#objectModal');if(d?.open)renderObject()}
function renderObject(){const id=document.querySelector('#objectId').value;const o=state.orders.find(x=>x.id===id);if(!o)return;const c=client(o.clientId);document.querySelector('#objectTitle').textContent=`${c?.name||'Клиент'} · ${o.size||'Дом'}`;document.querySelector('#objectSummary').innerHTML=`<div class="object-stat"><span>Готовность</span><strong>${progress(o)}%</strong></div><div class="object-stat"><span>Расходы</span><strong>${money(expenseTotal(o))}</strong></div><div class="object-stat"><span>Бригада</span><strong>${o.team.length} чел.</strong></div><div class="object-stat"><span>Документы</span><strong>${o.documents.length}</strong></div>`;document.querySelectorAll('.object-tab').forEach(b=>b.classList.toggle('active',b.dataset.objectTab===activeObjectTab));document.querySelector('#objectContent').innerHTML=renderObjectTab(o,c)}
function renderObjectTab(o,c){
  if(activeObjectTab==='overview')return `<div class="object-section"><div class="object-grid"><div class="object-box"><h4>Объект</h4><div class="mini-list"><div class="mini-row"><span>Клиент</span><strong>${esc(c?.name||'—')}</strong></div><div class="mini-row"><span>Адрес</span><strong>${esc(c?.address||'—')}</strong></div><div class="mini-row"><span>Дом</span><strong>${esc(o.size||'—')} ${o.area?'/ '+esc(o.area)+' м²':''}</strong></div><div class="mini-row"><span>Комплектация</span><strong>${esc(o.package||'—')}</strong></div></div></div><div class="object-box"><h4>Финансы</h4><div class="mini-list"><div class="mini-row"><span>Договор</span><strong>${money(o.price)}</strong></div><div class="mini-row"><span>Получено</span><strong>${money(o.prepayment)}</strong></div><div class="mini-row"><span>Расходы</span><strong>${money(expenseTotal(o))}</strong></div><div class="mini-row"><span>Остаток клиента</span><strong>${money(Math.max(0,(Number(o.price)||0)-(Number(o.prepayment)||0)))}</strong></div></div></div></div><div class="object-box"><h4>Этапы работ</h4><div class="stage-list">${o.buildStages.map((s,i)=>`<div class="stage-row"><label><input type="checkbox" ${s.done?'checked':''} onchange="toggleBuildStage('${o.id}',${i})">${esc(s.name)}</label><span class="muted">${s.done?'Готово':'В работе'}</span></div>`).join('')}</div></div></div>`;
  if(activeObjectTab==='expenses')return `<div class="object-section"><div class="object-box"><h4>Добавить расход</h4><form class="mini-form" onsubmit="addExpense(event,'${o.id}')"><input name="name" placeholder="Например: пиломатериал" required><div class="grid2"><input name="amount" type="number" min="0" placeholder="Сумма, ₽" required><input name="date" type="date" value="${today()}"></div><button class="primary" type="submit">+ Добавить расход</button></form></div><div class="object-box"><h4>Расходы · ${money(expenseTotal(o))}</h4><div class="mini-list">${o.expenses.length?o.expenses.map(x=>`<div class="mini-row"><span>${esc(x.name)}<br><small>${esc(x.date||'')}</small></span><strong>${money(x.amount)}</strong></div>`).join(''):'<div class="muted">Расходов пока нет</div>'}</div></div></div>`;
  if(activeObjectTab==='team')return `<div class="object-section"><div class="object-box"><h4>Добавить в бригаду</h4><form class="mini-form" onsubmit="addTeam(event,'${o.id}')"><input name="name" placeholder="Имя" required><div class="grid2"><input name="role" placeholder="Роль / специальность"><input name="phone" placeholder="Телефон"></div><button class="primary" type="submit">+ Добавить</button></form></div><div class="object-box"><h4>Бригада</h4><div class="mini-list">${o.team.length?o.team.map(x=>`<div class="mini-row"><span>${esc(x.name)}<br><small>${esc(x.role||'')} ${x.phone?'· '+esc(x.phone):''}</small></span><strong>${esc(x.role||'Рабочий')}</strong></div>`).join(''):'<div class="muted">Бригада не указана</div>'}</div></div></div>`;
  if(activeObjectTab==='docs')return `<div class="object-section"><div class="object-box"><h4>Добавить документ</h4><form class="mini-form" onsubmit="addDocument(event,'${o.id}')"><input name="name" placeholder="Договор, смета, акт..." required><input name="note" placeholder="Номер или комментарий"><button class="primary" type="submit">+ Добавить документ</button></form></div><div class="object-box"><h4>Документы</h4><div class="mini-list">${o.documents.length?o.documents.map(x=>`<div class="mini-row"><span>📄 ${esc(x.name)}<br><small>${esc(x.note||'')}</small></span><strong>${esc(x.date)}</strong></div>`).join(''):'<div class="muted">Документов пока нет</div>'}</div><div class="object-note">Сейчас CRM хранит карточки документов и заметки. Загрузку реальных файлов добавим после подключения облачного хранилища.</div></div></div>`;
  if(activeObjectTab==='photos')return `<div class="object-section"><div class="object-box"><h4>Фото стройки</h4><form class="mini-form" onsubmit="addPhoto(event,'${o.id}')"><input name="title" placeholder="Например: каркас первого этажа" required><input name="url" type="url" placeholder="Ссылка на фото (необязательно)"><button class="primary" type="submit">+ Добавить фото</button></form></div><div class="photo-grid">${o.photos.length?o.photos.map(x=>`<div class="photo-placeholder">${x.url?`<a href="${esc(x.url)}" target="_blank">📷 ${esc(x.title)}</a>`:`📷 ${esc(x.title)}`}<br><small>${esc(x.date)}</small></div>`).join(''):'<div class="photo-placeholder">Фото пока нет</div>'}</div><div class="object-note">Прямую загрузку фотографий с телефона подключим вместе с облачной базой и хранилищем.</div></div>`;
  if(activeObjectTab==='history')return `<div class="object-box"><h4>История объекта</h4>${o.history.length?o.history.map(x=>`<div class="history-item"><strong>${esc(x.text)}</strong><span>${esc(x.date)}</span></div>`).join(''):'<div class="muted">История пока пустая</div>'}</div>`;
  return '';
}
window.addExpense=(e,id)=>{e.preventDefault();const o=state.orders.find(x=>x.id===id);const f=new FormData(e.target);o.expenses.push({id:uid(),name:f.get('name'),amount:f.get('amount'),date:f.get('date')||today()});addHistory(o,`Добавлен расход: ${f.get('name')} — ${money(f.get('amount'))}`);save()};
window.addTeam=(e,id)=>{e.preventDefault();const o=state.orders.find(x=>x.id===id);const f=new FormData(e.target);o.team.push({id:uid(),name:f.get('name'),role:f.get('role'),phone:f.get('phone')});addHistory(o,`В бригаду добавлен: ${f.get('name')}`);save()};
window.addDocument=(e,id)=>{e.preventDefault();const o=state.orders.find(x=>x.id===id);const f=new FormData(e.target);o.documents.push({id:uid(),name:f.get('name'),note:f.get('note'),date:today()});addHistory(o,`Добавлен документ: ${f.get('name')}`);save()};
window.addPhoto=(e,id)=>{e.preventDefault();const o=state.orders.find(x=>x.id===id);const f=new FormData(e.target);o.photos.push({id:uid(),title:f.get('title'),url:f.get('url'),date:today()});addHistory(o,`Добавлено фото: ${f.get('title')}`);save()};

document.querySelectorAll('.object-tab').forEach(btn=>btn.addEventListener('click',()=>{activeObjectTab=btn.dataset.objectTab;renderObject()}));
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(v=>v.classList.remove('active'));document.querySelector('#'+id).classList.add('active');document.querySelector(`.nav-btn[data-view="${id}"]`)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));
document.querySelectorAll('[data-view-jump]').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.viewJump)));
document.querySelectorAll('[data-open]').forEach(btn=>btn.addEventListener('click',()=>document.querySelector('#'+btn.dataset.open).showModal()));
document.querySelectorAll('.close').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog').close()));
document.querySelector('#clientSearch').addEventListener('input',renderClients);document.querySelector('#orderSearch').addEventListener('input',renderOrders);document.querySelector('#buildSearch').addEventListener('input',renderBuilds);
document.querySelector('#clientForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.clients.push({id:uid(),name:f.get('name'),phone:f.get('phone'),messenger:f.get('messenger'),city:f.get('city'),address:f.get('address'),source:f.get('source'),date:f.get('date')||today(),comment:f.get('comment')});e.currentTarget.reset();e.currentTarget.closest('dialog').close();save()});
document.querySelector('#orderForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!f.get('clientId'))return alert('Сначала выберите клиента');const o={id:uid(),clientId:f.get('clientId'),size:f.get('size'),area:f.get('area'),package:f.get('package'),price:f.get('price'),prepayment:f.get('prepayment'),status:f.get('status'),startDate:f.get('startDate'),deadline:f.get('deadline'),comment:f.get('comment'),buildStages:defaultBuildStages(),expenses:[],team:[],documents:[],photos:[],history:[]};addHistory(o,'Создана сделка');state.orders.push(o);e.currentTarget.reset();e.currentTarget.closest('dialog').close();save()});
document.querySelector('#dealForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const o=state.orders.find(x=>x.id===f.get('id'));if(!o)return;const old=o.status;o.status=f.get('status');o.price=f.get('price');o.prepayment=f.get('prepayment');o.startDate=f.get('startDate');o.deadline=f.get('deadline');o.comment=f.get('comment');if(isBuild(o)&&!o.buildStages)o.buildStages=defaultBuildStages();if(old!==o.status)addHistory(o,`Статус изменён: ${old} → ${o.status}`);e.currentTarget.closest('dialog').close();save()});
document.querySelector('#resetBtn').addEventListener('click',()=>{if(confirm('Очистить все данные CRM на этом устройстве?')){state={clients:[],orders:[]};[PREV_KEY,OLD_KEY].forEach(k=>localStorage.removeItem(k));save()}});
renderAll();
